### ISSUE TITLE
커밋 메세지에 대해서

### ISSUE THREAD

**Issue by Sonchaegeon** [NIGHT-OWL-TEAM/findme-backend#1]
- CREATE <변경사항>
- DELETE <변경사항>
- UPDATE <변경사항>
- REPACTOR <변경사항>
- FIX <변경사항>

이런식으로 맞춰주세요!

**Comment by Sonchaegeon** [comment]
확인 답글 달고 close 부탁드립니다. @hwc9169

**Comment by hwc9169** [comment]
넵 알겠습니다
